
- name: functions
  hosts: local
  connection: local
  
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Rachel') }}" #Use Rachel is person variable is undefined

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}" #split function to convert string into list

  - name: convert map into list #list starts with hyphen (key:value) 
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items }}" 

  - name: convert list into map # map starts with space (keys,values)
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict }}"

  - name: convert to uppercase
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "Rachel Sigao"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: check IP address is valid or not
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}" # returns IP if valid else returns empty
